# Generated by Django 3.2.5 on 2022-02-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentBookings',
        ),
    ]
