# Generated by Django 3.2.5 on 2022-02-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_currentbookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookapointment',
            options={'verbose_name_plural': 'Book Appointment'},
        ),
    ]
