# Generated by Django 3.2.9 on 2022-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographers',
            name='photographer_pay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_account_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_name',
            field=models.CharField(max_length=30),
        ),
    ]
