# Generated by Django 3.2.9 on 2022-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220305_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_category',
            field=models.CharField(max_length=30),
        ),
    ]
