# Generated by Django 3.2.9 on 2022-03-26 13:17

import client.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_bookapointment_user_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographers',
            name='photographer_expertise',
            field=django_enumfield.db.fields.EnumField(default=0, enum=client.models.Category_types),
        ),
    ]
