# Generated by Django 3.2.9 on 2022-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_photographers_photographer_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_photographer',
            field=models.CharField(max_length=30),
        ),
    ]
