# Generated by Django 3.2 on 2022-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20220402_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_photographer',
            field=models.CharField(max_length=30),
        ),
    ]
