# Generated by Django 3.2 on 2022-04-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20220411_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.bookingcategories'),
        ),
        migrations.AlterField(
            model_name='bookapointment',
            name='user_booking_photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.photographers'),
        ),
    ]
